package com.kelvaya.ecobee.client

import com.kelvaya.util.jsonenum.JsonRangeEnum


/** Valid alert numbers found in [[Alert]] */
object AlertNumber extends JsonRangeEnum {

  val InvalidRegPassword = Val(611, "Invalid registration password")
  val ColdTemp = Val(1000, "Cold temp alert")
  val HotTemp = Val(1001, "Hot temp alert")
  val CompressShutdown = Val(1002, "Sensor activated shutting down compressor")
  val FurnaceError = Val(1003, "Problem with furnace/boiler heating")
  val HeatpumpError = Val(Seq(1004, 1005), "Problem with heatpump heating")
  val CoolingError = Val(1006, "Problem with cooling")
  val EICommunicationError = Val(1007, "Communication to EI failed")
  val AuxHeatRunningTooLong = Val(1009, "Problem with aux heat, running too much")
  val AuxHeatRunningOutsideTempHigh = Val(1010, "Aux heat used with high outdoor temp")
  val OccupiedDetected = Val(1011, "Sensor activated switching to occupied")
  val UnoccupiedDetected = Val(1012, "Sensor activated switching to unoccupied")
  val DisablingAC = Val(1013, "Sensor activated disabling AC")
  val SetTempUpDown = Val(1014, "Sensor activated setting temp up/down")
  val SensorActivated = Val(1015, "Sensor activated")
  val ActivateRelay = Val(1016, "Sensor activated opening/closing relay")
  val SwitchFanOn = Val(1017, "Sensor activated turning on fan")
  val ShutdownAuxHeat = Val(1018, "Sensor activated shutting down aux heat")
  val ShutdownHeatingCooling = Val(1019, "Sensor activated shutting down heating/cooling")
  val LoHumidity = Val(1020, "Low humidity alert")
  val HiHumidity = Val(1021, "High humidity alert")
  val ShutdownHeat = Val(1022, "Sensor activated shutting down heat")
  val ActivateHumidifier = Val(1024, "Sensor activated humidifier")
  val ActivateDehumidifier = Val(1025, "Sensor activated dehumidifier")
  val LowBattery = Val(1026, "Low battery")
  val RemoteSensorDetected = Val(1027, "Remote sensor detected")
  val RemoteSensorNotCommunicating = Val(1028, "Remote sensor not communicating")
  val RemoteSensorReestablished = Val(1029, "Remote sensor re-established")
  val InvalidCurrentTemp = Val(1030, "Invalid current temp reading")
  val CurrentTempReadingRestored = Val(1031, "Current temp reading restored")
  val BadHumiditySensor = Val(Seq(1032, 1033), "Faulty humidity sensor")
  val BadZigbeeModuleInstalled = Val(1034, "Incorrect Zigbee module installed")
  val FurnaceMaintenance = Val(3130, "Furnace maintenance reminder")
  val HumidifierMaintenance = Val(3131, "Humidifier maintenance reminder")
  val VentilatorMaintenance = Val(3132, "Ventilator maintenance reminder")
  val DehumidifierMaintenance = Val(3133, "Dehumidifier maintenance reminder")
  val EconomizerMaintenance = Val(3134, "Economizer maintenance reminder")
  val UVMaintenance = Val(3135, "UV maintenance reminder")
  val ACMaintenance = Val(3136, "AC maintenance reminder")
  val AirFilterMaintenance = Val(3137, "Air filter reminder (ClimateMaster only)")
  val AirCleanerMaintenance = Val(3138, "Air cleaner reminder (ClimateMaster only)")
  val HVACMaintenance = Val(3140, "Hvac maintenance reminder")
  val ClimateTalk = Val(4000, "ClimateTalk")
  val ClimateTalkFault = Val(4100 to 4199, "ClimateTalk device alert major/minor fault codes")
  val ClimateTalkNotCommunicating = Val(4200 to 4299, "ClimateTalk device lost communications")
  val ClimateTalkSysMessage = Val(4300 to 4399, "ClimateTalk system message from device")
  val DRVoluntaryAlert = Val(6000, "DR voluntary alert")
  val DRVoluntaryUtilityMessage = Val(6001, "DR voluntary utility message")
  val DRVoluntaryAlerts = Val(6002 to 6005, "DR voluntary alerts")
  val DRMandatoryAlert = Val(Seq(6100, 6102), "DR mandatory alert")
  val DRMandatoryMessage = Val(6101, "DR mandatory message")
  val MonthlyCostExceeded = Val(6200, "Monthly cost exceeded")
  val MonthlyProjectedCostExceeded = Val(6201, "Monthly projected cost exceeded")
  val NetworkJoinSuccess = Val(6300, "Network join successful")
  val NetworkJoinFail = Val(6301, "Network join failed")
  val RegistrationConfirmed = Val(7000, "Registration confirmation")
  val RegistrationReminder = Val(7001, "Registration Remind me alert")
  val WebMessage = Val(7002, "Web initiated messages - such as Utility welcome message or similar")
  val DaikinAlert = Val(8000 to 8299, "Daikin Indoor/Outdoor Unit Alerts")
  val ClimateMasterHeatpumpAlert = Val(8300 to 8599, "ClimateMaster Heatpump/hardware Unit Alerts")
  val ClimateMasterFault = Val(9000, "ClimateMaster fault")
  val ClimateMasterFaultMax = Val(9255, "ClimateMaster fault max")
  val ClimateMasterDisconnected = Val(9500, "ClimateMaster disconnected")
  val ClimateMasterDisconnectedMax = Val(9755, "ClimateMaster disconnected max")
}