package com.kelvaya.ecobee.client

import com.kelvaya.util.enum.JsonStringEnum
import com.kelvaya.util.SprayImplicits
import com.kelvaya.util.Time

import spray.json.DefaultJsonProtocol._

/** An alert generated either by a thermostat or user which requires user attention
  *
  * @param acknowledgeRef The unique alert identifier
  * @param date The alert date
  * @param time The alert time
  * @param severity The alert severity.
  * @param text The alert message text
  * @param alertNumber The ecobee alert message identifier.
  * @param alertType The type of alert this is.
  * @param isOperatorAlert Whether the alert was generated by the thermostat owner
  * @param reminder Whether a reminder will be sent.
  * @param showIdt Whether to show the alert on the thermostat.
  * @param showWeb Whether to show the alert on the ecobee web portal.
  * @param sendEmail Whether to send an alert email to the thermostat user.
  * @param acknowledgement The user acknowledgement type.
  * @param remindMeLater Whether to remind the user at a later time about the alert.
  * @param thermostatIdentifier The identifier of the thermostat that generated the alert
  * @param notificationType The type of Alert or reminder
  */
case class Alert(
    acknowledgeRef :       String,
    date :                 Time.DateOnly,
    time :                 Time.TimeOnly,
    severity :             Alert.Severity,
    text :                 String,
    alertNumber :          Alert.Number,
    alertType :            Alert.Type,
    isOperatorAlert :      Boolean,
    reminder :             Boolean,
    showIdt :              Boolean,
    showWeb :              Boolean,
    sendEmail :            Boolean,
    acknowledgement :      Alert.Ack,
    remindMeLater :        Boolean,
    thermostatIdentifier : String,
    notificationType :     Alert.NotificationType
)


object Alert extends SprayImplicits {
  type Type = AlertType.Entry
  type Ack = AlertAck.Entry
  type NotificationType = AlertNotificationType.Entry
  type Severity = AlertSeverity.Entry
  type Number = AlertNumber.Entry

  implicit val AlertFormat = jsonFormat16(Alert.apply)
}


/** Types of [[Alert]] records */
object AlertType extends JsonStringEnum {
  val Alert = Val("alert")
  val DemandResponse = Val("demandResponse")
  val Emergency = Val("emergency")
  val Message = Val("message")
  val Pricing = Val("pricing")
}


/** Types of user acknowledgments on [[Alert alerts]] */
object AlertAck extends JsonStringEnum {
  val Accept = Val("accept")
  val Decline = Val("decline")
  val Defer = Val("defer")
  val Unacknowledged = Val("unacknowledged")
}


/** Notification types triggered for an [[Alert]].
  *
  * @see [[NotificationSettings]]
  */
object AlertNotificationType extends JsonStringEnum {
  val Alert = Val("alert")
  val HVAC = Val("hvac")
  val Furnace = Val("furnaceFilter")
  val Humidifer = Val("humidifierFilter")
  val Dehumidifer = Val("dehumidifierFilter")
  val Ventilator = Val("ventilator")
  val AC = Val("ac")
  val AirFilter = Val("airFilter")
  val AirCleaner = Val("airCleaner")
  val UV = Val("uvLamp")
  val Temperature = Val("temp")
  val LoTemp = Val("lowTemp")
  val HiTemp = Val("highTemp")
  val LoHumidity = Val("lowHumidity")
  val HiHumidity = Val("highHumidity")
  val AuxHeat = Val("auxHeat")
  val AuxOutdoor = Val("auxOutdoor")
}


/** Levels of [[Alert]] severities */
object AlertSeverity extends JsonStringEnum {
  val High = Val("high")
  val Medium = Val("medium")
  val Low = Val("low")
}

